### ISSUE TITLE
ban on CgV

### ISSUE THREAD

**Issue by guskant** [lojban/jbovlaste#148]
jbovlaste and camxes should be revised according to the conclusion of BPFK. We have now the updated morphology page:
https://groups.google.com/d/msg/bpfk-list/OH-sdfvlXsY/L7wxPvSsJTAJ

Move the words that include CgV strings into "obsolete fu'ivla" or "obsolete cmavo" category.

**Comment by teleological** [comment]
Depends on teleological/camxes-py#7

**Comment by teleological** [comment]
Updated vlatai to teleological/camxes-py#8 (v135 morphology). Marked all non-conforming words as obsolete.
