### ISSUE TITLE
Handle non-existent {word} in comment threads better

### ISSUE THREAD

**Issue by maikxlx** [lojban/jbovlaste#151]
Currently, if a word (e.g. zei'e) enclosed in curly braces in comment doesn't exist in the DB, then the comment thread displays something like "Word zei'e not found in database" right in the comment text.  

I suggest that we remove the verbiage and simply print the word.  The link can point to the add page Wikipedia-style in red if desired, e.g.

http://jbovlaste.lojban.org/dict/addvalsi.html?valsi=zei%27i

...which will be visible in most current browsers when you mouse-over the link.  The link can also remain as-is if that's preferred.

**Comment by durka** [comment]
This is necessary in the notes and examples too. See the example: http://jbovlaste.lojban.org/dict/jvame%27o

At least there should be a way to escape the curly braces, but printing it in red is better pe'i.

**Comment by mezohe** [comment]
.e'u jai gau tcita lo dei se liste lo ka mulno

**Comment by durka** [comment]
Closed by #178.
