### ISSUE TITLE
jbovlaste does not recognize some valid lujvo

### ISSUE THREAD

**Issue by selpahi** [lojban/jbovlaste#157]
Perhaps this has to do with xorxes' recent morphology bug fix not having been implemented in jbovlaste yet. Examples would be "akti'ygau" and "aktygau", both of which are to be considered correct. I think it was durka who added this fix to the PEGs we're using in the bots.

**Comment by teleological** [comment]
I remember xorxes and durka iterating on some issues. If you think it has stabilized, I will add the latest changes and re-run them against the contents of jbovlaste to confirm them.

**Comment by teleological** [comment]
Possibly related to #148.

**Comment by lagleki** [comment]
Yes, e.g. the master ilmentufa is up to date.

**Comment by teleological** [comment]
{aktygau} is considered a valid lujvo by camxes-py/vlatai v0.7, which is the current version used by jbovlaste. This is based on morphology v119. I started investigating the impact of upgrading the morphology to v134 which I suspect will cover {akti'ygau}, etc.

**Comment by teleological** [comment]
Updated jbovlaste vlatai to use teleological/camxes-py#8 (v135 morphology). Now accepts {akti'ygau} as a lujvo.
