### ISSUE TITLE
Saving definitions with NON-ASCII characters garbles them in view mode

### ISSUE THREAD

**Issue by lagleki** [lojban/jbovlaste#164]
Example: http://jbovlaste.lojban.org/dict/ci'oi

This UTF problem appears only after you resave existing definitions with NON-ASCII characters.

XML dumps also contain garbled text of newly added or newly edited definitions.

Definitely connected to the latest changes to libs on the server.

**Comment by teleological** [comment]
This didn't work. Investigating further.

**Comment by teleological** [comment]
I think this is working now for editing definitions. A similar change may be necessary for adding new definitions, and it will be necessary to identify and fix any definitions that were corrupted since this problem was introduced, so leaving this bug open.

**Comment by teleological** [comment]
I think this now works for adding and editing, and I re-encoded the affected definitions, but suspect there may be other encoding bugs lurking. Please file new issues as such issues are discovered.
