### ISSUE TITLE
Can't submit “ky bu”

### ISSUE THREAD

**Issue by Wuzzy2** [lojban/jbovlaste#170]
I tried to submit “ky bu” (A bu-letteral for “q”, see https://lojban.github.io/cll/17/5/), but Jbovlaste crashes. “kybu”, however works, but this is actually not correct, because the pause between “ky” and “bu” is mandatory.

**Comment by lagleki** [comment]
probably related to https://github.com/lojban/jbovlaste/issues/78

**Comment by selpahi** [comment]
The pause is not mandatory, but a space should still be allowed.

**Comment by Wuzzy2** [comment]
It seems to be fixed now.
