### ISSUE TITLE
Etymology data displays “foreign” characters incorrectly

### ISSUE THREAD

**Issue by Wuzzy2** [lojban/jbovlaste#171]
Example:

http://jbovlaste.lojban.org/dict/judrnporte

In my broswer, English etymology is shown as something like this:

> From English âportâ.

When I click the edit button, it is correctly shown as:

> From English “port”.

**Comment by teleological** [comment]
Reopening as reminder to repair encodings on/after 1431705478

**Comment by teleological** [comment]
Fixed encoding on etymologies for {judrnporte}, {tranrzalpetre}, {puvrmipmepi}, {sizrmipmepi}, and {gernciba'inu}.
