### ISSUE TITLE
Online Dictionary does not support non-ASCII characters

### ISSUE THREAD

**Issue by Pendrokar** [lojban/jbovlaste#199]
Example:
http://jbovlaste.lojban.org/lookup.pl?Form=lookup.pl2&Database=*&Query=catke

Does not seem to be due to a lacking '<meta charset="UTF-8">' tag, rather with the information rendered/printed.

**Comment by rlpowell** [comment]
That page looks fine to me?; can you explain the problem in more detail?

**Comment by Pendrokar** [comment]
If my memory was that good, I could. I vaguely remember that the page either had a 500 error or simply did not find anything.

Closing this issue.
