### ISSUE TITLE
Issue in jbovlaste English pdf export

### ISSUE THREAD

**Issue by lancioni** [lojban/jbovlaste#202]
There is a problem in the pdf Printable Dictionary for English: the output ends at page 442 (last entry pevyca’o zei uidje). The .tex file seems to be complete; unfortunately, MikTeX gives me errors and I cannot produce the pdf file myself. I guess there is some offending instruction in the .text file.

Greetings,

Giuliano

**Comment by lagleki** [comment]
duplicate of https://github.com/lojban/jbovlaste/issues/180
