### ISSUE TITLE
private key?

### ISSUE THREAD

**Issue by dented42** [lojban/jbovlaste#205]
I'm not expert but this really seems like something that doesn't belong in a public repository.

https://github.com/lojban/jbovlaste/blob/1bd38c741641805d0d69829b8b960057c9ad133a/export/xml-export.html#L51-L52

**Comment by rlpowell** [comment]
Meh.  It just gives you the ability to do automated xml exports; if
the system starts getting abused that way we'll eventually notice
the slowdown and change the key.
