### ISSUE TITLE
Error in generating printable dictionary

### ISSUE THREAD

**Issue by lancioni** [lojban/jbovlaste#207]
When trying to export English-Lojban dictionary, the following error occurs:

error: | Error  in tempdir() using /tmp/jbovlaste_export/XXXXXXXXXX: Parent directory  (/tmp/jbovlaste_export) does not exist at  /srv/jbovlaste/current/export/latex-export.html line 9.
-- | --
context: | ...                        287:           local @CARP_NOT = $cgc ? $cgc->() : caller();                 288:           shortmess_heavy(@_);                 289:       }                 290:                        291:       sub croak   { die shortmess @_ }                 292:       sub confess { die longmess @_ }                 293:       sub carp    { warn shortmess @_ }                 294:       sub cluck   { warn longmess @_ }                 295:                        ... | ... |   | 287: | local @CARP_NOT = $cgc ? $cgc->() : caller(); | 288: | shortmess_heavy(@_); | 289: | } | 290: |   | 291: | sub croak   { die shortmess @_ } | 292: | sub confess { die longmess @_ } | 293: | sub carp    { warn shortmess @_ } | 294: | sub cluck   { warn longmess @_ } | 295: |   | ... |  
... |  
287: | local @CARP_NOT = $cgc ? $cgc->() : caller();
288: | shortmess_heavy(@_);
289: | }
290: |  
291: | sub croak   { die shortmess @_ }
292: | sub confess { die longmess @_ }
293: | sub carp    { warn shortmess @_ }
294: | sub cluck   { warn longmess @_ }
295: |  
... |  
code stack: | /usr/share/perl5/vendor_perl/Carp.pm:291         /usr/share/perl5/vendor_perl/File/Temp.pm:1704         /srv/jbovlaste/current/export/latex-export.html:9         /usr/share/perl5/vendor_perl/HTML/Mason/Request.pm:948         /srv/jbovlaste/mason-data-dir/obj/3306348060/jbovlaste/export/latex-export.html.obj:17         /srv/jbovlaste/current/autohandler:4

Raw error:

Error in tempdir() using /tmp/jbovlaste_export/XXXXXXXXXX: Parent directory (/tmp/jbovlaste_export) does not exist at /srv/jbovlaste/current/export/latex-export.html line 9.

Trace begun at /usr/share/perl5/vendor_perl/HTML/Mason/Exceptions.pm line 125
HTML::Mason::Exceptions::rethrow_exception('Error in tempdir() using /tmp/jbovlaste_export/XXXXXXXXXX: Parent directory (/tmp/jbovlaste_export) does not exist at /srv/jbovlaste/current/export/latex-export.html line 9.^J') called at /usr/share/perl5/vendor_perl/Carp.pm line 291
Carp::croak('Error in tempdir() using /tmp/jbovlaste_export/XXXXXXXXXX: Parent directory (/tmp/jbovlaste_export) does not exist') called at /usr/share/perl5/vendor_perl/File/Temp.pm line 1704
File::Temp::tempdir('DIR', '/tmp/jbovlaste_export/') called at /srv/jbovlaste/current/export/latex-export.html line 9
HTML::Mason::Commands::__ANON__('lang', 'en') called at /usr/share/perl5/vendor_perl/HTML/Mason/Component.pm line 157
HTML::Mason::Component::run_dynamic_sub('HTML::Mason::Component::FileBased=HASH(0x7f3cfcf60338)', 'main', 'lang', 'en') called at /usr/share/perl5/vendor_perl/HTML/Mason/Request.pm line 948
HTML::Mason::Request::call_dynamic('HTML::Mason::Request::ApacheHandler=HASH(0x7f3cf002a4a0)', 'main', 'lang', 'en') called at /srv/jbovlaste/mason-data-dir/obj/3306348060/jbovlaste/export/latex-export.html.obj line 17
HTML::Mason::Commands::__ANON__('lang', 'en') called at /usr/share/perl5/vendor_perl/HTML/Mason/Component.pm line 135
HTML::Mason::Component::run('HTML::Mason::Component::FileBased=HASH(0x7f3cfcf60338)', 'lang', 'en') called at /usr/share/perl5/vendor_perl/HTML/Mason/Request.pm line 1302
eval {...} at /usr/share/perl5/vendor_perl/HTML/Mason/Request.pm line 1292
HTML::Mason::Request::comp(undef, undef, undef, 'lang', 'en') called at /usr/share/perl5/vendor_perl/HTML/Mason/Request.pm line 1355
HTML::Mason::Request::scomp('HTML::Mason::Request::ApacheHandler=HASH(0x7f3cf002a4a0)', 'HTML::Mason::Component::FileBased=HASH(0x7f3cfcf60338)', 'lang', 'en') called at /srv/jbovlaste/current/autohandler line 4
HTML::Mason::Commands::__ANON__('lang', 'en') called at /usr/share/perl5/vendor_perl/HTML/Mason/Component.pm line 135
HTML::Mason::Component::run('HTML::Mason::Component::FileBased=HASH(0x7f3cfcc8f108)', 'lang', 'en') called at /usr/share/perl5/vendor_perl/HTML/Mason/Request.pm line 1300
eval {...} at /usr/share/perl5/vendor_perl/HTML/Mason/Request.pm line 1292
HTML::Mason::Request::comp(undef, undef, undef, 'lang', 'en') called at /usr/share/perl5/vendor_perl/HTML/Mason/Request.pm line 481
eval {...} at /usr/share/perl5/vendor_perl/HTML/Mason/Request.pm line 481
eval {...} at /usr/share/perl5/vendor_perl/HTML/Mason/Request.pm line 433
HTML::Mason::Request::exec('HTML::Mason::Request::ApacheHandler=HASH(0x7f3cf002a4a0)') called at /usr/share/perl5/vendor_perl/HTML/Mason/ApacheHandler.pm line 168
HTML::Mason::Request::ApacheHandler::exec('HTML::Mason::Request::ApacheHandler=HASH(0x7f3cf002a4a0)') called at /usr/share/perl5/vendor_perl/HTML/Mason/ApacheHandler.pm line 825
HTML::Mason::ApacheHandler::handle_request('HTML::Mason::ApacheHandler=HASH(0x7f3cfc009a80)', 'Apache2::RequestRec=SCALAR(0x7f3cf4038b80)') called at (eval 31) line 8
HTML::Mason::ApacheHandler::handler('HTML::Mason::ApacheHandler', 'Apache2::RequestRec=SCALAR(0x7f3cf4038b80)') called at -e line 0
eval {...} at -e line 0

![immagine](https://user-images.githubusercontent.com/3199462/60759582-d1784680-a027-11e9-9361-1afd0ae06cba.png)

**Comment by Pendrokar** [comment]
Similar error here: http://jbovlaste.lojban.org/dict/centi

**Comment by rlpowell** [comment]
Long since fixed.
