### ISSUE TITLE
XML Export: Never ends loading the page in English

### ISSUE THREAD

**Issue by Robin-3** [lojban/jbovlaste#208]
https://jbovlaste.lojban.org/export/xml-export.html?lang=en

**Comment by lynn** [comment]
Maybe your browser is having trouble loading a huge XML file into memory and displaying it. I've had better luck grabbing the XML exports using right click → "Save as…"

**Comment by rlpowell** [comment]
It certainly may have been broken before, but yes at this moment it works with Save As, whereas for my in Chrome attempting to load it causes an out of memory error.
