### ISSUE TITLE
ko sidju! Lost password

### ISSUE THREAD

**Issue by DGCK81LNN** [lojban/jbovlaste#212]
I am [`DGCK81LNN` on jbovlaste](https://jbovlaste.lojban.org/personal/DGCK81LNN) (with email `triluolnn@163.com` which is also my verified email on GitHub, visible on [my GitHub profile page](https://github.com/DGCK81LNN)) and unfortunately I have forgotten my password. Can I have my password reset?

**Comment by rlpowell** [comment]
You know at the bottom of every page it says what to do if you are having problems and this isn't it.  :D  I'll followup with you in email.

**Comment by DGCK81LNN** [comment]
Oh, I apologize for not having seen the bottom notice. Thank you for the help.
