### ISSUE TITLE
XML export does not contain words with score ≤0

### ISSUE THREAD

**Issue by lynn** [lojban/jbovlaste#213]
I'd like a way to get all words, not just positively voted ones. For example "cibvanbi" exists in the database but has score -1, so it's not in en.xml.

**Comment by lynn** [comment]
Opposite of https://github.com/lojban/jbovlaste/issues/55 :) 

Maybe `xml-export.html?lang=en` could retain its current behavior, and adding `&all=true` could export all entries, even "bad" ones.

**Comment by Ntsekees** [comment]
Yeah, having this as an option would be nice.

**Comment by rlpowell** [comment]
Try now!
